### ISSUE TITLE
surf96

### ISSUE THREAD

**Issue by a649473624** [jbrussell/SURF96_Rayl_1Dinv#1]
Hello, may I ask how to solve this problem.

 'chmod' Not an internal or external command, nor a runnable program  
Or batch files.  
The function 'card2mod' corresponding to the input parameter of type 'char' is not defined.

**Comment by jbrussell** [comment]
I think I have fixed the card2mod issue. You can simply add the line 
`addpath('./functions/')`
to the top of the main script.

As for the chmod issue, I assume you are on Windows? It is trying to call a unix command to change the permissions of the executables. This will only work on Mac, unfortunately. You might be able to find a work around for Windows, but I'm afraid I won't be of much help there.

**Comment by a649473624** [comment]
Thank you, Sir. I'm trying to find a solution for Windows.

**Comment by 24986759510525** [comment]
Hello, I would like to ask how to solve this problem

/Bin/bash:/ Bin_ V3.30/surf96: Unable to execute binary file
Rm: Unable to delete 'temp. dsp': No file or directory available
